### PR TITLE
fix/create incentives page

### LINKED ISSUE #302: fix(incentives): error message
The creation of incentives can fail for multiple reasons for example:
- not enough whale in wallet
- flow start too far in the future
- flow end too far in the future
- flow duration too long

That should be communicated to the user via the (disabled) primary button

### LINKED ISSUE #472: display the needed whale fee for incentive flow
Open a incentive flow costs 1000 whale, this is not visible on the frontend right now

If you want to report a security issue, please follow our security policy: `https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/docs/SECURITY.md`

---

## Steps to Reproduce

1. Navigate to `P` page and begin to
2. Execute `X` transaction on the `vault` contract 
3. ... 
4. ... 

**Expected results:** 

**Actual results:** 

---

### Additional context

Add any other context about the problem here, code snippets, json responses and so on.

<details>
<summary>Screen shots</summary>

</details>

<details>
  <summary>Logs</summary>

```

```

</details>

### PR DESCRIPTION
**Pull request by jijicodes**
## Description and Motivation
Screenshot 2024-03-07 at 2 16 54 PM

- Added a fee field

- Updated a couple of error messages on the button label

## Related Issues
Resolves #302, Resolves #472 
---

## Checklist:

- [x] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/CONTRIBUTING.md).
- [x] My pull request has a sound title and description (not something vague like `Update index.md`)
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation.
- [x] The code is formatted properly `yarn lint`.
- [x] The project builds and is able to deploy on Netlify `yarn build`.

### CODE REVIEW

File: components/Pages/Trade/Incentivize/Create.tsx [hunk 1]
```diff
@@ -120,25 +126,38 @@ const Create = ({ poolId }: Props) => {
...
         />
       </HStack>
 
+      <Divider opacity="0.2" />
+
+      <HStack justifyContent="space-between" minWidth={['280', '340']}>
+        <Text color="whiteAlpha.600">Fee</Text>
+        <HStack spacing="1" direction="row" alignItems={'baseline'}>
+          <Text >
+        1000</Text>
```
Comment (nick134-bit) [inline components/Pages/Trade/Incentivize/Create.tsx:144]: `<Divider opacity="0.2" paddingY={'2'}/>

      <HStack justifyContent="space-between">
        <Text color="whiteAlpha.600">Fee</Text>
        <Spacer />
        <Text>1000</Text>
        <Text fontSize={12}>WHALE</Text>
      </HStack>
`

**Review by nick134-bit — APPROVED** [review]
